language: cpp
compiler: g++
install: export CXX=g++-4.8
before_script:
- sudo apt-get update -qq
- sudo apt-get install libboost-dev
- sudo apt-get install libtbb-dev
script:
  - make
  - make test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
