language: cpp
compiler: g++
install: export CXX=g++-4.8
script:
  - make
  - make test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.8
      - libtbb-dev
      - libboost-dev
      - llvm-3.6-dev
